// =========================================================================================================================================
// generate-changelog.ts — regenerate CHANGELOG.md from src/releases/changelog.yaml
// Usage: pnpm generate-changelog
//
// CHANGELOG.md is a generated artifact — edit src/releases/changelog.yaml instead.
// =========================================================================================================================================

import { writeFileSync } from "node:fs";
import { readChangelog } from "./changelog-utils.ts";

const CHANGELOG_OUT = "CHANGELOG.md";

const data = readChangelog();

// Build the Markdown file header: generated-file notice, title, standards links, and opening separator
const lines: string[] = [
    "<!-- Generated by pnpm generate-changelog — edit src/releases/changelog.yaml instead -->",
    "# Changelog",
    "",
    "All notable changes to this project will be documented in this file.",
    "Format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).",
    "This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).",
    "",
    "---",
    "",
];

// Emit a versioned section for each release in reverse-chronological order (newest first in the YAML)
for (const entry of data.releases) {
    lines.push(`## [${entry.version}] — ${entry.date}`);
    lines.push("");

    if (entry.added?.length) {
        lines.push("### Added");
        lines.push("");
        for (const item of entry.added) lines.push(`- ${item}`);
        lines.push("");
    }
    if (entry.changed?.length) {
        lines.push("### Changed");
        lines.push("");
        for (const item of entry.changed) lines.push(`- ${item}`);
        lines.push("");
    }
    if (entry.fixed?.length) {
        lines.push("### Fixed");
        lines.push("");
        for (const item of entry.fixed) lines.push(`- ${item}`);
        lines.push("");
    }
    if (entry.security?.length) {
        lines.push("### Security");
        lines.push("");
        for (const item of entry.security) lines.push(`- ${item}`);
        lines.push("");
    }

    lines.push("---");
    lines.push("");
}

writeFileSync(CHANGELOG_OUT, lines.join("\n"), "utf8");
console.log(`✓ ${CHANGELOG_OUT} regenerated from src/releases/changelog.yaml`);
